---
title: Не зіткнись!
hero_image: images/banner.png
description:
  Створи нескінченну гру-раннер, де твій персонаж повинен уникнути зіткнення з перешкодами
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Ти зробиш
  - title: Вибір теми
  - title: Створення перешкод
    completion:
      - engaged
  - title: Виявлення зіткнень
  - title: Швидше!
    completion:
      - internal
  - title: Швидкий тест
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Вдосконалення твого проєкту
  - title: Поділитися
  - title: Що далі?
