---
title: Niet botsen!
hero_image: images/banner.png
description:
  - Bouw een eindeloos 'runner game' waarin je personage moet voorkomen dat hij botst
  - met obstakels
meta_title: Python programmeerprojecten voor kinderen en tieners | Niet botsen!
meta_description: Leer Python met de codeerprojecten van de Raspberry Pi Foundation voor kinderen en tieners. Bouw een scrollend runner-spel in Python en vermijd obstakels.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Wat ga je maken
  - title: Het opzetten van de scene
  - title: Maak een obstakel
    completion:
      - engaged
  - title: Willekeurige obstakels
  - title: Veel obstakels
  - title: Botsingen
    completion:
      - internal
  - title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Uitdaging
    challenge: true
  - title: Wat kun je verder nog doen?
