---
title: Niet botsen!
hero_image: images/banner.png
description:
  - Bouw een 'runner game' waarin je personage moet voorkomen dat hij botst
  - met obstakels
meta_title: Python programmeer projecten voor kinderen en tieners | Niet botsen!
meta_description: Leer Python met de codeerprojecten van de Raspberry Pi Foundation voor kinderen en tieners. Bouw een scrollend runner-spel in Python en vermijd obstakels.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: What you will make
  - 
    title: Set the scene
  - 
    title: Create an obstacle
    completion:
      - engaged
  - 
    title: Random obstacles
  - 
    title: Lots of obstacles
  - 
    title: Collisions
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: Wat kun je verder nog doen?
