---
title: Don't collide!
hero_image: images/banner.png
description:
  Build an endless runner game where your character must avoid colliding
  with obstacles
meta_title: Python coding projects for kids and teens | Don't collide!
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Build a scrolling runner game in Python and avoid obstacles.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: What you will make
  - title: Set the scene
  - title: Create obstacles
    completion:
      - engaged
  - title: Lots of obstacles
  - title: Collisions
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade your project
  - title: Share
  - title: What next?
