---
title: '¡No choques!'
hero_image: images/banner.png
description:
  - 
  - 
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: You will make
  - 
    title: Elige el tema
  - 
    title: Crea los obstáculos
    completion:
      - engaged
  - 
    title: Detección de choques
  - 
    title: '¡Acelera!'
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Mejora tu proyecto
  - 
    title: Comparte
  - 
    title: '¿Qué sigue?'
