name: "Don't Collide: Dodge Asteroids"
identifier: "dodge-asteroids-example"
COMPONENTS:
  - name: "main"
    extension: "py"
    location: "main.py"
    index: 0
    default: true
IMAGES:
  - "moon.png"
  - "rocket.png"
