---
title: Osgoi'r rhwystrau!
hero_image: images/banner.png
description:
  - 
  - 
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: You will make
  - 
    title: Gosod y thema
  - 
    title: Creu rhwystrau
    completion:
      - engaged
  - 
    title: Canfod gwrthdrawiad
  - 
    title: Cyflymu pethau!
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Uwchraddio dy brosiect
  - 
    title: Rhannu
  - 
    title: Beth nesaf?
