---
title: Não colida!
hero_image: images/banner.png
description:
  - 
  - 
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Você vai fazer
  - 
    title: Defina o tema
  - 
    title: Crie obstáculos
    completion:
      - engaged
  - 
    title: Detecção de colisão
  - 
    title: Acelere!
    completion:
      - internal
  - 
    title: Questionário rápido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Atualize seu projeto
  - 
    title: Compartilhar
  - 
    title: E agora?
