---
title: Não colida!
hero_image: images/banner.png
description:
  - Construa um jogo de corrida sem fim onde seu personagem deve evitar colisões
  - com obstáculos
meta_title: Projetos de codificação Python para crianças e adolescentes | Não colida!
meta_description: Aprenda Python com os projetos de codificação da Raspberry Pi Foundation para crianças e adolescentes. Crie um jogo de corrida com rolagem em Python e evite obstáculos.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: What you will make
  - 
    title: Set the scene
  - 
    title: Create an obstacle
    completion:
      - engaged
  - 
    title: Random obstacles
  - 
    title: Lots of obstacles
  - 
    title: Collisions
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: E agora?
