---
title: Nie zderzaj się!
hero_image: images/banner.png
description:
  - Zbuduj niekończącą się grę dla biegaczy, w której twoja postać musi unikać kolizji
  - z przeszkodami
meta_title: Python projekty kodowania dla dzieci i młodzieży | nie zderzaj się!
meta_description: Naucz się języka Python z projektami programistycznymi Fundacji Raspberry Pi dla dzieci i młodzieży. Zbuduj grę z przewijaniem biegacza w Pythonie i unikaj przeszkód.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Zrobisz to
  - 
    title: Ustaw motyw
  - 
    title: Tworzenie przeszkód
    completion:
      - engaged
  - 
    title: Wykrywanie kolizji
  - 
    title: Przyspiesz!
    completion:
      - internal
  - 
    title: Szybki quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Ulepsz swój projekt
  - 
    title: Udostępnij
  - 
    title: Co dalej?
