---
title: Don't collide!
hero_image: images/banner.png
description:
  - 
  - 
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: You will make
  - 
    title: Set the theme
  - 
    title: Create obstacles
    completion:
      - engaged
  - 
    title: Collision detection
  - 
    title: Speed up!
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Ulepsz swój projekt
  - 
    title: Udostępnij
  - 
    title: Co dalej?
