---
title: Pas de collision !
hero_image: images/banner.png
description:
  - 
  - 
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Définir le thème
  - 
    title: Créer des obstacles
    completion:
      - engaged
  - 
    title: Détection de collision
  - 
    title: Accélérer !
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Partager
  - 
    title: Et ensuite ?
