---
title: Pas de collision !
hero_image: images/banner.png
description:
  - Construis un jeu de course sans fin où ton personnage doit éviter d'entrer en collision
  - avec des obstacles
meta_title: Projets de codage Python pour enfants et adolescents | Pas de collision !
meta_description: Apprends le langage Python avec les projets de codage de la Raspberry Pi Foundation pour les enfants et les adolescents. Construis un jeu de course sans fin où ton personnage doit éviter d'entrer en collision avec des obstacles.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Ce que tu vas faire
  - title: Définir le thème
  - title: Créer des obstacles
    completion:
      - engaged
  - title: Détection de collision
  - title: Accélérer !
    completion:
      - internal
  - title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Améliorer ton projet
  - title: Partager
  - title: Et ensuite ?
